config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'
  get '/search' => 'pages#search', as: :pages_search

  resources :users

  resources :flights do
    resources :reservations
  end
  resources :airplanes

end

app/models/airplane.rb
# == Schema Information
#
# Table name: airplanes
#
#  id         :integer          not null, primary key
#  name       :string
#  columns       :integer
#  columns    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Airplane < ActiveRecord::Base
  has_many :flights
  validates :rows, :numericality => {:less_than_or_equal_to => 50, :greater_than => 0}
  validates :columns, :numericality => {:less_than_or_equal_to => 7, :greater_than => 0}
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplane = Airplane.new
    @current_user = User.find_by(:name => 'Admin')
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new(airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to flights_path, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airplane_params
      params.require(:airplane).permit(:name, :rows, :columns)
    end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_for(@airplane) do |f| %>
  <% if @airplane.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@airplane.errors.count, "error") %> prohibited this airplane from being saved:</h2>

      <ul>
      <% @airplane.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Plane Model:" %><br>
    <%= f.text_field :name, required: true %>
  </div>
  <div class="field">
    <%= f.label "Rows (max 30):" %><br>
    <%= f.number_field :rows, required: true %>
  </div>
  <div class="field">
    <%= f.label "Columns(max 7):" %><br>
    <%= f.number_field :columns, required: true %>
  </div>

  <div class="actions">
    <%= result = f.submit %>
    <!-- <%#= result = f.submit %> -->
  </div>

<% end %>


<button id="save">Save</button>

<button id="cancel">Cancel</button>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form' %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>
<nav>
  Admin View |
  <%= link_to 'Flights', flights_path %> |
  <%= link_to 'New Plane', airplanes_path %>
</nav>
<br>
<%= render 'form' %>

<hr>

<div id = "plane_name"> </div>

<div id="holder">
  <ul id="place">

  </ul>
</div>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form' %>

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airplane.name %>
</p>

<p>
  <strong>Rows:</strong>
  <%= @airplane.rows %>
</p>

<p>
  <strong>Columns:</strong>
  <%= @airplane.columns %>
</p>

<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>