config/routes.rb
Rails.application.routes.draw do
  root 'pages#homepage'
  get '/search' => 'pages#search', as: :pages_search

  resources :users

  resources :flights do
    resources :reservations
  end
  resources :airplanes

end

app/views/pages/homepage.html.erb
<h1>Burning Airlines homepage</h1>


<button><%= link_to "Admin", flights_path %></button> | <button><%= link_to "User", new_user_path %></button>

app/views/pages/search.html.erb
<p id="notice"><%= notice %></p>

<h2>Search flights</h2>

<!-- this will direct to pages search path on submit -->
<%= form_tag(pages_search_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search_origin, params[:search_origin], placeholder: "Origin" %>
  <%= text_field_tag :search_destination, params[:search_destination], placeholder: "Destination" %>
  <%= submit_tag "Let's Go!", :name => nil %>
<% end %>

<% if @flights.blank? %>
  <h4>There are no flights available from <%= params[:search_origin] %> to <%= params[:search_destination]%>.</h4>
<% else %>
  <h3>Flights</h3>

  <table>
    <thead>
      <tr>
        <th>Date</th>
        <th>Flight</th>
        <th>From</th>
        <th>To</th>
        <th>Plane</th>
        <th>Capacity</th>
        <th>Remaning</th>
      </tr>
    </thead>

    <tbody>
      <% @flights.each do |flight| %>
        <tr>
          <td><%= flight.date %></td>
          <td><%= link_to flight.number, flight_path(flight) %></td>
          <td><%= "#{flight.origin}" %></td>
          <td><%= "#{flight.destination}" %></td>
          <td><%= flight.airplane.name %></td>
          <td><%= flight.capacity %></td>
          <td><%= flight.remaining %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>